# Generated by Django 4.2.29 on 2026-03-25 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("used", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("base", "Base"), ("excess", "Excess")],
                        default="base",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "packages",
            },
        ),
    ]
