# Generated by Django 4.2.29 on 2026-03-25 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WhatsApp", "WhatsApp"),
                            ("Instagram", "Instagram"),
                            ("Facebook", "Facebook"),
                            ("Site", "Site"),
                            ("Outros", "Outros"),
                        ],
                        default="WhatsApp",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("qualified", "Qualified"),
                            ("in_progress", "In Progress"),
                            ("forwarded", "Forwarded"),
                            ("disqualified", "Disqualified"),
                            ("reengagement", "Re-engagement"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("interactions", models.IntegerField(default=0)),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("disqualification_reason", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leads",
                "unique_together": {("tenant", "phone")},
            },
        ),
    ]
