# Generated by Django 4.2.29 on 2026-03-25 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_info", models.TextField(blank=True, default="")),
                ("icp", models.TextField(blank=True, default="")),
                ("qualification_criteria", models.JSONField(default=list)),
                (
                    "tone_of_voice",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("casual", "Casual"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("re_engagement_enabled", models.BooleanField(default=False)),
                ("re_engagement_delay_hours", models.IntegerField(default=24)),
                ("re_engagement_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_config",
            },
        ),
    ]
